### ISSUE TITLE
Add new maintainer to feedstock

### ISSUE THREAD

**Issue by connorjbracy** [conda-forge/regolith-feedstock#32]
Hi @CJ-Wright and @scopatz, sorry if this is not the correct way of going about this but I am a PhD student in Professor Billinge's group currently helping out with software maintenance. In order to complete my tasks, I will need to be added as a maintainer to the `regolith-feedstock` repo. It appears that Professor Billinge is not yet listed as a maintainer. When you get a chance, could you please add one or both of us as a maintainer?

 @sbillinge, please confirm that this information is correct.

**Comment by sbillinge** [comment]
closed by #33
